# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Riza Erdi Karakuş
title: iOS Developer
email: karakusrizaerdi@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  karakuserdi
linkedin_username: rizaerdikarakus

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Riza Erdi Karakuş. I graduated from the Computer Engineering department at Maltepe University. After graduation, I worked on several projects using ASP.NET and later decided to learn Swift programming language. As an iOS Developer, I have been working at a company for about a year, where I have been involved in many projects.

  Developing several projects has enhanced my analytical skills, allowing me to provide suitable solutions to both my team members and clients. Collaborating and working in a team to successfully complete projects brings me great satisfaction.
  
  My interest in technology motivates me to continue learning and developing myself. Therefore, I take time to research and implement new technologies.

  My goal is to continue growing both personally and professionally by investing in self-education. In the future, I see myself working on bigger and more challenging projects and being recognized as a technology leader.

  I hope this information is sufficient. If you would like to know more about me, please do not hesitate to contact me. Thank you.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ToDoApp
        link: github.com/karakuserdi/ToDoApp
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/karakuserdi/ToDoApp
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           December 2022 - December 2022
        description: | # this will include new lines to allow paragraphs
          TodoList is an application that allows users to add their tasks in a sequence and create a shopping list. This project is developed in the swift programming language and uses sqlite for the backend. It is developed using the Viper design pattern. The biggest challenge in this project was using the Viper pattern correctly.
          
          With this project, users can add their tasks in a sequence and mark them as completed whenever they want. They can also create a shopping list and update it at any time. This application will help users to stay organized and keep track of their tasks.
      - layout: top-middle
        title: MiniHR
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           April 2022 - June 2022
        description: | # this will include new lines to allow paragraphs
          MiniHr simplifies the tracking of company activities and allows employees to see their leave requests, projects they are working on, and the time they spend on these projects. This application also keeps users informed of internal company activities.
      - layout: top-middle
        title: Aleefy
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           November 2022 - January 2023
        description: | # this will include new lines to allow paragraphs
          MAleefy is a veterinarian application that provides all the health services needed by pet owners. With this application, you can easily track your pet's health processes, communicate with other pet owners through the socialization section, and share your pet's photos or videos. Aleefy also shows you the nearest veterinary clinics to ensure that your pet gets the health services as soon as possible. This project is developed to make the lives of pet owners easier.
      - layout: top-middle
        title: DonatBi
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           July 2022 - Continues
        description: | # this will include new lines to allow paragraphs
          With our project called Donatbi, we have developed a food ordering application where users can order food to their address whenever they want. The application also allows users to order from restaurants and pick up their food at their desired time. Users can also make reservations at restaurants and pay for their meals online without wasting time.          
      - layout: top-middle
        title: Noisely
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           February 2023 - February - 2023
        description: | # this will include new lines to allow paragraphs
          Noisely is a mobile app that allows users to play multiple sounds at the same time and create customized sound lists. With weekly and monthly subscription options, users can access the full version of the app according to their preferences. It is an ideal tool for those who need to work, focus or relax in noisy environments.

          We focused on user needs and ease of use when developing Noisely. The app is regularly updated to provide the best user experience.
      - layout: top-middle
        title: BTOB
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           January 2023 - April 2023
        description: | # this will include new lines to allow paragraphs
          The B2B application I developed using the Swift programming language is a tool that facilitates direct communication and commercial transactions between businesses. The application includes features such as product catalogs, price lists, order tracking, and a user-friendly interface, which can accelerate and streamline the business process. Additionally, the application can help businesses increase customer satisfaction and gain a competitive advantage. This project demonstrates my Swift programming skills and my ability to understand the needs of businesses.
      - layout: top-middle
        title: BCloud
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           February 2023 - April 2023
        description: | # this will include new lines to allow paragraphs
          Bcloud is an in-house management application specially designed to perform management tasks quickly and efficiently. The application, developed in Swift language, is easily accessible by users on the iOS platform.
      - layout: top-middle
        title: QuakeSafe
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        additional_links:
          - title:  Download on the App Store
            url: https://apps.apple.com/us/app/quakesafe/id1672663845
        quote: >
           February 2023 - February 2023
        description: | # this will include new lines to allow paragraphs
          QuakeSafe is an emergency app designed to help those in need during an earthquake. It's equipped with special features like sound and flash alerts to help rescuers find you easily. It also includes a list of emergency numbers for quick dialing. Download QuakeSafe now and stay safe during an earthquake. Have a reliable app to assist you in times of crisis.
      - layout: top-middle
        title: SparrowAI
        # link_text: Project Website
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           March 2023 - Continues
        description: | # this will include new lines to allow paragraphs
          SparrowAI is an AI-powered application designed to make it easy for users to acquire information. The application, which works using ChatGPT, can provide accurate answers to all kinds of questions. SparrowAI is a learning system that can understand user requests and provide appropriate responses.

          SparrowAI provides quick, effective, and accurate answers on all kinds of subjects. Through a customizable interface based on queries, users can input their questions directly by typing or speaking. SparrowAI is designed to provide answers to all kinds of questions using natural language processing and machine learning technologies.

          SparrowAI is an application that can be used in many sectors. For example, customer service or sales departments can quickly and effectively respond to user questions. Additionally, SparrowAI becomes better over time thanks to its learning ability, providing more value to users.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TRtek MEDICAL SOFTWARE
        link: www.trtekyazilim.com
        # link_text: 
        sub_title: Software Intern
        caption: August 2021 - September 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
            l started to work 2 August in TRTek software as a ASP.NET Core developer. I took part in the development and establishment of the hospital information management system program.
      - layout: left
        title: Fenerbahçe University
        link: www.fbu.edu.tr
        # link_text: 
        sub_title: Software Developer
        caption: November 2021 - April 2022
        #quote: >
        description: | # this will include new lines to allow paragraphs
            I worked as a software developer focusing on API development using .NET at Fenerbahçe University for a period of six months. During this time, I collaborated with the team to understand the requirements, designed and implemented the APIs, and conducted testing and debugging. Additionally, I worked with my colleagues to ensure that our software development practices were aligned with industry standards.
      - layout: left
        title: ArafasApps
        link: www.arafas.com
        # link_text: 
        sub_title: iOS Developer
        caption: April 2022 - Present
        #quote: >
        description: | # this will include new lines to allow paragraphs
            I have been working as an iOS developer at ArafasApps for approximately a year, where I have been involved in a wide range of projects, including Minihr, Donatbi, Aleefy, Btob, White Noise, Bcloud, and more. During this time, I have gained valuable experience in designing and implementing iOS applications, collaborating with project teams, and providing solutions to complex challenges. This experience has helped me hone my skills as a developer and has prepared me for tackling new challenges in the field.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Maltepe University
        caption: 2018 - 2021
        sub_title: Bachelor's Degree, Computer Engineering
        description: | # this will include new lines to allow paragraphs
            In 2018, l registered Maltepe University Computer Engeneer department and l greduated from there in 2021.
      - layout: left
        title: Maltepe University
        caption: 2014 - 2017
        sub_title: Associate's Degree, Computer Programming
        description: | # this will include new lines to allow paragraphs
            When l go back to Turkey l registered at Maltepe University computer programming department and l graduated in 2017.
      - layout: left
        title: University of Vienna
        caption: 2010 - Dropout
        sub_title: Bachelor's Degree, Computer Science
        description: | # this will include new lines to allow paragraphs
            l lived in for 3 years. Firstly, I took a German course for 1.5 years, after I finished the German course, I enrolled in the school. But having to go back to turkey due to economic conditions.

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Turkish - Advanced
      - English - Good
      - German - Medium

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - IOS Application Development (UIKit - SwiftUI)
      - Alamofire, Kingfisher, URLSession
      - SQLite - Firebase
      - C#, ASP.NET Core

      Design Patterns
      - MVC,MVVM,VIPER Pattern

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
